<a href="https://colab.research.google.com/github/ronita00/Python_Django/blob/main/IT20048.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

enter on of Dept of f_engg:4
enter on of Dept of f_ls:5
enter on of Others department:9
Total department of MBSTU: 18


In [ ]:
def series():
    n = int(input("Input a number: "))
    sum_num = (n * (n + 1)) / 2
    return sum_num
print("sum of numbers:", series())

Input a number: 5
sum of numbers: 15.0


In [4]:
import numpy as np
test= np.array([1,2,3])
for i in test:
  print (str(i)+"\n")


1

2

3



In [20]:
# type(test)
# test.shape

# test1=np.array([[1,2,3],[4,5,6]])
# test1.shape

# test1.shape

test2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array shape:",test2.shape)
for i in test2:
  print(i)

Array shape: (3, 3)
[1 2 3]
[4 5 6]
[7 8 9]


In [34]:
test2=np.array ( [[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Array shape:",test2.shape)
for i in range(test2.shape[0]):
  for j in range(test2.shape[1]):
    print(test2[i][j],end=" ")
  print(" ")

Array shape: (3, 3)
1 2 3  
4 5 6  
7 8 9  


In [36]:
test2=np.array ( [[[1, 2, 3],[4, 5, 6],[7, 8, 9]],
               [[10,11,12],[13,14,15],[16,17,18]]])
print("Array shape:",test2.shape)
for i in test2:
  for j in i:
    for k in j:
      print(k,end=" ")
    print(" ")
  print(" ")

Array shape: (2, 3, 3)
1 2 3  
4 5 6  
7 8 9  
 
10 11 12  
13 14 15  
16 17 18  
 
